name: Austin
favicon: null
layout_spectrum: 0.16002314700745046
typography_spectrum: 0.1162483838852495
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12472950434312224
  lightness: 0.13858451531268656
  saturation: 0.3130046068690717
  rhythmicContrast: 0.5523356806952506
purpose: []
