name: Austin
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56434
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f4fcff'
    - '#010000'
    - '#5a6b7e'
    - '#90a2b0'
    - '#cfcfcf'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
